### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by mschae16** [daomeow/mod_0_skills#1]
@daomeow - Hi Melanie, you performed well enough on the assessment to merit a chance to make some changes that can promote you to `technical ready` status. Please make the following updates by EOD tomorrow (Monday):

- [x] It looks like you included instances that are both `Restaurant` classes. Could you update one of your class/instance example pairs to be a different type of class? For example, you could make a class called `Employee` or a class called `MenuItem` instead of giving both examples as `Restaurant`.

- [x] Make sure that your class names are singular and **PascalCase** as that is the normal naming convention.

- [x] Be sure to use _action verbs_ for all your method names - for example, `getCustomerToStaffRatio` instead of `customerToStaffRate`

- [x] In your variables.txt file, could you take another look at _how to re-assign variables_ in Javascript?  Looks like you declared `var food` twice.

- [x] Be sure to check that everything is spelled and formatted correctly.

Let me know if you have any questions!

**Comment by daomeow** [comment]
@mschae16 - Hi Margo! I have made my updates to the Master branch. Thank you.

**Comment by mschae16** [comment]
@daomeow - Thanks for updating this! You are officially `technical ready`!
